package:
  name: concurrentqueue
  version: 20171101

source:
  git_url: https://github.com/cameron314/concurrentqueue.git
  git_rev: 7b69a8fd4d7dfbc169bd79aa724a3e8da19b9851

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
